# Generated by Django 6.1 on 2026-08-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('RECEIPT_APPROVED', 'Receipt Approved'), ('RECEIPT_REJECTED', 'Receipt Rejected'), ('MEDIA_APPROVED', 'Media Approved'), ('MEDIA_REJECTED', 'Media Rejected'), ('NEW_INQUIRY', 'New Inquiry'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired'), ('REPORT_REVIEWED', 'Report Reviewed')], max_length=30),
        ),
    ]
