# Generated by Django 6.1 on 2026-09-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('RECEIPT_APPROVED', 'Receipt Approved'), ('RECEIPT_REJECTED', 'Receipt Rejected'), ('MEDIA_APPROVED', 'Media Approved'), ('MEDIA_REJECTED', 'Media Rejected'), ('NEW_INQUIRY', 'New Inquiry'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired'), ('REPORT_REVIEWED', 'Report Reviewed'), ('ADVERTISEMENT_PAYMENT_APPROVED', 'Advertisement Payment Approved'), ('ADVERTISEMENT_PAYMENT_REJECTED', 'Advertisement Payment Rejected'), ('ADVERTISEMENT_EXPIRING', 'Advertisement Expiring'), ('ADVERTISEMENT_EXPIRED', 'Advertisement Expired')], max_length=30),
        ),
    ]
