# Generated by Django 6.1 on 2026-09-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('RECEIPT_APPROVED', 'Receipt Approved'), ('RECEIPT_REJECTED', 'Receipt Rejected'), ('MEDIA_APPROVED', 'Media Approved'), ('MEDIA_REJECTED', 'Media Rejected'), ('NEW_INQUIRY', 'New Inquiry'), ('NEW_MESSAGE', 'New Message'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired'), ('REPORT_REVIEWED', 'Report Reviewed')], max_length=30),
        ),
    ]
