# Generated by Django 6.0.4 on 2026-09-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='media_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
