# Generated by Django 6.1 on 2026-09-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_businesslisting_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslisting',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
