# Generated by Django 6.1 on 2026-08-21 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('seller_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media', to='seller_subscriptions.sellersubscription'),
        ),
    ]
