# Generated by Django 6.0.4 on 2026-09-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='business_media/'),
        ),
    ]
