# Generated by Django 6.1 on 2026-09-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='business_media/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DEACTIVATED', 'Deactivated')], default='PENDING_REVIEW', max_length=20),
        ),
    ]
