# Generated by Django 6.1 on 2026-09-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_description_media_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DEACTIVATED', 'Deactivated')], default='PENDING_REVIEW', max_length=20),
        ),
    ]
