# Generated by Django 6.0.4 on 2026-09-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_savedlisting'),
        ('seller_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersubscription',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='listings.businesslisting'),
        ),
    ]
