# Generated by Django 6.1 on 2026-09-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('seller_subscriptions', '0003_alter_sellersubscription_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellersubscription',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_subscription', to='listings.businesslisting'),
        ),
    ]
